//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveAuth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiveAuth.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not found..
        /// </summary>
        public static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application key &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateApplicationName {
            get {
                return ResourceManager.GetString("DuplicateApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant key &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateTenantName {
            get {
                return ResourceManager.GetString("DuplicateTenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application key &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidApplicationName {
            get {
                return ResourceManager.GetString("InvalidApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant key &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidTenantName {
            get {
                return ResourceManager.GetString("InvalidTenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have an email address, phone number, or email address to register..
        /// </summary>
        public static string MustHaveEmailPhoneOrUsername {
            get {
                return ResourceManager.GetString("MustHaveEmailPhoneOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application security stamp cannot be null..
        /// </summary>
        public static string NullApplicationSecurityStamp {
            get {
                return ResourceManager.GetString("NullApplicationSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant security stamp cannot be null..
        /// </summary>
        public static string NullTenantSecurityStamp {
            get {
                return ResourceManager.GetString("NullTenantSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IApplicationSecurityStampStore&lt;TApplication&gt;..
        /// </summary>
        public static string StoreNotIApplicationSecurityStampStore {
            get {
                return ResourceManager.GetString("StoreNotIApplicationSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableApplicationStore&lt;TApplication&gt;..
        /// </summary>
        public static string StoreNotIQueryableApplicationStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableApplicationStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableTenantStore&lt;TTenant&gt;..
        /// </summary>
        public static string StoreNotIQueryableTenantStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableTenantStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement ITenantSecurityStampStore&lt;TTenant&gt;..
        /// </summary>
        public static string StoreNotITenantSecurityStampStore {
            get {
                return ResourceManager.GetString("StoreNotITenantSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant not found..
        /// </summary>
        public static string TenantNotFound {
            get {
                return ResourceManager.GetString("TenantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
    }
}
